# install: conda env create -f behavysis_viewer_dev.yaml
# update: conda env update -f behavysis_viewer_dev.yaml --prune

name: behavysis_viewer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - nb_conda
  - ffmpeg
  - pip:
      - behavysis_viewer
