# install: conda env create -f ba_viewer_dev.yaml
# update: conda env update -f ba_viewer_dev.yaml --prune

name: ba_viewer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - nb_conda
  - ffmpeg
