# install: conda env create -f ba_viewer_dev.yaml
# update: conda env update -f ba_viewer_dev.yaml --prune

name: ba_viewer_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - setuptools
  - pip
  - ipykernel
  - pydantic
  - numpy
  - pandas
  - scipy
  - pyarrow
  - opencv
  - pyqtgraph
  - matplotlib
  - pyside6
  - natsort
  - tqdm
  # dev packages
  - black
  - pytest
  - mkdocs-material
  - mkdocstrings-python
  - pip:
      - -e "../"
