# install: conda env create -f behavysis_viewer_dev.yaml
# update: conda env update -f behavysis_viewer_dev.yaml --prune

name: behavysis_viewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - ipykernel
  - ffmpeg
  - hdf5
  - pip:
      - behavysis_viewer
